services:
  kryx-dev:
    build:
      context: ./api
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - kryx-dev-data:/data
      - ./api/autosend:/app/autosend
      - /var/log/kryx-dev:/var/log/kryx-dev
    container_name: kryx-dev
    image: kryx-dev
    ports:
      - "127.0.0.1:8002:8000"
    restart: unless-stopped
    environment:
      TZ: Africa/Johannesburg

volumes:
  kryx-dev-data:
    name: kryx-dev-data
